'use strict';

/**
 * CSS emitter — step 14b.
 *
 * Converts resolved theme tokens into a site.css file with --sb-* CSS custom
 * properties, plus utility class rules for component layouts and recipe classes.
 *
 * Output rules (from api_implementation_brief):
 *   - CSS variables with --sb- prefix
 *   - component class naming per naming contract (c-{component}, c-{component}__{slot})
 *   - no inline styles from content payload
 */

const { flattenTokens } = require('../resolver/token-resolver');

/**
 * Convert a dotted token path to a CSS variable name.
 * e.g. "color.primary" → "--sb-color-primary"
 */
function toCssVar(tokenPath) {
    return '--sb-' + tokenPath.replace(/\./g, '-').replace(/_/g, '-');
}

/**
 * Emit the :root block with all CSS custom properties from theme tokens.
 */
function emitRootVars(tokens) {
    const flat = flattenTokens(tokens);
    const lines = Object.entries(flat)
        .filter(([, v]) => typeof v === 'string' || typeof v === 'number')
        .map(([path, value]) => `  ${toCssVar(path)}: ${value};`);
    return `:root {\n${lines.join('\n')}\n}\n`;
}

/**
 * Emit base layout utility classes used by the layout_recipe values.
 */
function emitLayoutUtilities() {
    return `
/* Layout utilities */
.layout-full-width { width: 100%; }
.layout-single-column { max-width: var(--sb-layout-container-max-width, 1120px); margin: 0 auto; padding: 0 var(--sb-layout-gutter, 24px); }
.layout-two-column { display: grid; grid-template-columns: 1fr 1fr; gap: var(--sb-layout-gutter, 24px); }
.layout-grid-3 { display: grid; grid-template-columns: repeat(3, 1fr); gap: var(--sb-layout-gutter, 24px); }
.layout-stack { display: flex; flex-direction: column; gap: var(--sb-spacing-scale-2, 8px); }

@media (max-width: 768px) {
  .layout-two-column, .layout-grid-3 { grid-template-columns: 1fr; }
}
`;
}

/**
 * Emit component base class rules from component recipes in the render plan.
 * Uses resolved token values from render plan.
 */
function emitComponentClasses(renderPlan) {
    const seenComponents = new Set();
    const rules = [];

    for (const page of renderPlan.pages || []) {
        for (const region of page.regions || []) {
            for (const instance of region.components || []) {
                const cls = instance.dom.root_class;
                if (seenComponents.has(cls)) continue;
                seenComponents.add(cls);

                const tokens = instance.styles && instance.styles.tokens || {};
                const props = [];

                if (tokens.surface && tokens.surface !== 'transparent') {
                    props.push(`  background-color: ${tokens.surface};`);
                }
                if (tokens.padding && tokens.padding !== '0') {
                    props.push(`  padding: ${tokens.padding};`);
                }
                if (tokens.radius && tokens.radius !== '0') {
                    props.push(`  border-radius: ${tokens.radius};`);
                }
                if (tokens.shadow && tokens.shadow !== 'none') {
                    props.push(`  box-shadow: ${tokens.shadow};`);
                }
                if (tokens.border && tokens.border !== 'transparent') {
                    props.push(`  border: 1px solid ${tokens.border};`);
                }

                if (props.length > 0) {
                    rules.push(`.${cls} {\n${props.join('\n')}\n}`);
                }

                // Slot classes
                for (const slot of instance.dom.slots || []) {
                    const slotCls = slot.class_name;
                    const slotProps = [];
                    if (slot.element === 'h1' && tokens.title_scale) {
                        slotProps.push(`  font-size: ${tokens.title_scale};`);
                    }
                    if (slot.element === 'p' && tokens.text_scale) {
                        slotProps.push(`  font-size: ${tokens.text_scale};`);
                    }
                    if (slotProps.length > 0) {
                        rules.push(`.${slotCls} {\n${slotProps.join('\n')}\n}`);
                    }
                }
            }
        }
    }

    return rules.join('\n\n');
}

/**
 * Emit the full site.css.
 *
 * @param {object} renderPlan  render_plan_v1
 * @param {object} tokens      theme-pack.tokens
 * @returns {string} CSS content
 */
function emitCss(renderPlan, tokens) {
    return [
        `/* Site CSS — generated by web-compiler. DO NOT EDIT. */`,
        `/* Theme: ${renderPlan.resolved_tokens.theme_id} | Profile: ${renderPlan.resolved_tokens.polish_profile_id} */`,
        '',
        emitRootVars(tokens),
        emitLayoutUtilities(),
        emitComponentClasses(renderPlan),
    ].join('\n');
}

module.exports = { emitCss, toCssVar };
