'use strict';

/**
 * JS behaviour manifest emitter — step 14c.
 *
 * Produces a minimal site.js that registers behaviour hooks declared in the
 * render plan's behaviour_manifest.  No layout logic — hooks only.
 *
 * Output rules (from api_implementation_brief):
 *   - behaviour hooks only
 *   - no layout logic in JS
 *   - hook names use js: prefix in manifest
 */

/**
 * Generate the initialiser body for a known hook kind.
 */
function hookInitialiser(hookName, instanceId) {
    const name = hookName.replace(/^js:/, '');
    switch (name) {
        case 'tabs':
            return `
  // Tabs hook: ${instanceId}
  (function() {
    var root = document.querySelector('[data-component][data-variant]');
    if (!root) return;
    var tabs = root.querySelectorAll('[role="tab"]');
    var panels = root.querySelectorAll('[role="tabpanel"]');
    tabs.forEach(function(tab, i) {
      tab.addEventListener('click', function() {
        tabs.forEach(function(t) { t.setAttribute('aria-selected', 'false'); });
        panels.forEach(function(p) { p.hidden = true; });
        tab.setAttribute('aria-selected', 'true');
        if (panels[i]) panels[i].hidden = false;
      });
    });
    if (tabs[0]) tabs[0].click();
  })();`;
        default:
            return `
  // Hook: ${hookName} on instance ${instanceId}`;
    }
}

/**
 * Emit site.js from the behaviour manifest.
 *
 * @param {Array} behaviourManifest  render_plan.behaviour_manifest
 * @returns {string} JS content
 */
function emitJs(behaviourManifest) {
    if (!behaviourManifest || behaviourManifest.length === 0) {
        return `/* site.js — no behaviour hooks registered */\n`;
    }

    const initialisers = behaviourManifest.map(entry =>
        hookInitialiser(entry.hook, entry.instance_id)
    ).join('\n');

    return `/* site.js — generated by web-compiler. DO NOT EDIT. */
/* Behaviour hooks only. No layout logic. */
(function() {
  'use strict';
  document.addEventListener('DOMContentLoaded', function() {
${initialisers}
  });
})();
`;
}

module.exports = { emitJs };
